package Budget;

import Notifications.Notification;
import data.DataManager;

import java.io.Serializable;
import java.util.Date;

/**
 * Represents an alert generated by the system when a budget crosses a threshold.
 *
 * <p>US#5 seq: Budget.checkThreshold() → BudgetAlert.generate() → Notification.create(type, message)
 * <p>US#10 seq: checkThreshold(): void → Budget → BudgetAlert.generate(): void
 *                                   → Notification.create(type:String, message:String): Notification
 *
 * @author DebugSquad
 * @version 1.0
 */
public class BudgetAlert implements Serializable {

    private int     alertId;
    private int     budgetId;
    private int     userID;          // needed to create Notification
    private String  type;            // "NEAR_LIMIT", "EXCEEDED"
    private String  message;
    private Date    timestamp;
    private boolean isRead;

    /**
     * Constructs an empty {@code BudgetAlert}.
     */
    public BudgetAlert() {}

    /**
     * Constructs a new {@code BudgetAlert}.
     *
     * @param budgetId the ID of the budget triggering the alert
     * @param userID   the ID of the user to notify
     * @param type     the type of alert ("NEAR_LIMIT" or "EXCEEDED")
     * @param message  the alert message text
     */
    public BudgetAlert(int budgetId, int userID, String type, String message) {
        this.budgetId  = budgetId;
        this.userID    = userID;
        this.type      = type;
        this.message   = message;
        this.timestamp = new Date();
        this.isRead    = false;
    }

    /**
     * Legacy constructor (without userID).
     *
     * @param budgetId the ID of the budget
     * @param type     the type of alert
     * @param message  the alert message text
     */
    public BudgetAlert(int budgetId, String type, String message) {
        this(budgetId, 0, type, message);
    }

    /**
     * Generates the alert and creates a corresponding system notification.
     *
     * <p>US#5 seq: Budget → BudgetAlert.generate(): void
     *            BudgetAlert → Notification.create(type, message): Notification
     * <p>US#10 seq: BudgetAlert.generate(): void → Notification.create(type,message)
     *
     * @param type    the new alert type
     * @param message the new alert message
     */
    public void generate(String type, String message) {
        this.type      = type;
        this.message   = message;
        this.timestamp = new Date();
        this.isRead    = false;

        System.out.println("\n BUDGET ALERT: [" + type + "] " + message);

        // US#5 & US#10: create(type, message): Notification
        if (userID > 0) {
            Notification notif = new Notification(userID, type, message);
            DataManager.addNotification(notif);
            System.out.println("  [Notification created for user " + userID + "]");
        }
    }

    /**
     * Creates and returns a new {@code BudgetAlert} instance based on current details.
     *
     * @param type    the alert type
     * @param message the alert message
     * @return a new populated {@code BudgetAlert}
     */
    public BudgetAlert create(String type, String message) {
        BudgetAlert alert = new BudgetAlert(budgetId, userID, type, message);
        System.out.println(" Alert created: [" + type + "] " + message);
        return alert;
    }

    /**
     * Simulates sending the alert directly.
     */
    public void send() {
        System.out.println("[BudgetAlert] Sent: [" + type + "] " + message);
    }

    /**
     * Marks this alert as read by the user.
     */
    public void markAsRead() {
        this.isRead = true;
        System.out.println("Alert marked as read: " + this.message);
    }

    
    /** @return the alert ID */
    public int     getAlertId()    { return alertId; }
    /** @param id the new alert ID */
    public void    setAlertId(int id) { this.alertId = id; }
    /** @return the associated budget ID */
    public int     getBudgetId()   { return budgetId; }
    /** @param id the associated budget ID */
    public void    setBudgetId(int id) { this.budgetId = id; }
    /** @return the user ID */
    public int     getUserID()     { return userID; }
    /** @param id the user ID */
    public void    setUserID(int id) { this.userID = id; }
    /** @return the type of alert */
    public String  getType()       { return type; }
    /** @param t the type of alert */
    public void    setType(String t) { this.type = t; }
    /** @return the alert message */
    public String  getMessage()    { return message; }
    /** @param m the alert message */
    public void    setMessage(String m) { this.message = m; }
    /** @return the time the alert was created */
    public Date    getTimestamp()  { return timestamp; }
    /** @param d the time the alert was created */
    public void    setTimestamp(Date d) { this.timestamp = d; }
    /** @return {@code true} if marked as read */
    public boolean isRead()        { return isRead; }
    /** @param r {@code true} to mark as read */
    public void    setRead(boolean r) { this.isRead = r; }
}